### ISSUE TITLE
line started with ;  gets executed

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#102]
All lines are commented out but the interpreter still prints some result

```
;(:= (length Nil) 0)
;(:= (length (Cons $a $m))
;    (+ 1 (length $m))
;)

; !(println! (match &self (:= (length Nil $W) True) (+ 1 $W) )                )

```

expected result: interpreter doesn't print result of match query

**Comment by Necr0x0Der** [comment]
`;` doesn't comment out a line, it is an expression that comments out the next expression
you can basically write just:
```
;(:= (length (Cons $a $m))
    (+ 1 (length $m))
)
```
`!` is also an expression, and it tells the system to interpret the next expression instead of adding it to the Space. This is a temporal solution, which is not in the MeTTa core, but in unit tests now. This will hopefully be changed in the future.
