### ISSUE TITLE
MeTTa type checker in Rust cannot match two parameterized types

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#130]
The following MeTTa code

```scheme
;; Declaration of List data structure
(: List (-> $a Type))
(: Nil (List $a))
(: Cons (-> $a (List $a) (List $a)))

!(println! ("========= Test equality ========="))
!(println! (== True True))
!(println! (== True False))
!(println! (== Nil Nil))
!(println! (== 1 1))
!(println! (== (Cons 1 Nil) (Cons 1 Nil)))
```

prints

```
("========= Test equality =========")
True
False
True
[]
[]
[]
[]
[]
[]
```

If the type declarations of `List`, `Nil` and `Cons` are removed, then it prints

```
("========= Test equality =========")
True
False
(== Nil Nil)
True
(== (Cons 1 Nil) (Cons 1 Nil))
[]
[]
[]
[]
[]
[]
```

What does that mean?

Generally speaking should I overload `==` for non primary data types?

Last and least, what do the `[]`s mean?

**Comment by Necr0x0Der** [comment]
A side remark. `metta.py` now prints all the results gathered in the course of execution of the script (including empty results). So, you don't need to write `!(println! (== True True))`, because `println!` will print `True`, but then `metta.py` will print `[]` as the result of evaluation of `println!` itself. You can simply write `! (== True True)`. However, if you find this inconvenient, we can change this back.

Regarding the issue itself... hmm.... Let me make a few remarks. `==` is a grounded symbol of `(-> $t $t Bool)` type with automatic argument wrapping / unwrapping (which basically means that it expects Python grounded atoms as arguments). Before, passing non-grounded symbols to such operations caused Python exceptions, which, however, were ignored, so the expression was not reduced. Now, exceptions are not ignored, but returned as atoms. However, passing a non-grounded symbol of a possibly correct type (e.g., `Undefined`) is explicitly considered not as an exception, but as a reason for not reducing the expression. So, when `Nil` is not typed, returning `(== Nil Nil)` without reduction is perfectly correct. When the input atoms are typed and types are incorrect, such expressions are allowed atm (if automatic type checking is not turned on), but their evaluation leads to the empty result (see some explanations in `scripts/b5_types_prelim.metta`). However, since `==` has type `(-> $t $t Bool)`, so it should actually accept `Nil` of type `(List $a)`.

It seems that the bug is not related to grounded symbols, and a pure example would be:
```
(: eq (-> $t $t Type))
(: a (A $a))
(: b (A $a))
!(eq a b)
```

It doesn't work, indeed (the result is empty). For `(: a A)`, `(: b A)`, the result is correctly non-empty. And for `(: a A)`, `(: b B)` the result is correctly empty. But it doesn't work even for `(: a $a)`, `(: b $a)`. So, runtime type acceptance for polymorphic types seems to be incomplete, @vsbogd .

**Comment by vsbogd** [comment]
Thanks, for spotting this, I will look at it after finishing with variables substitution issue.
