### ISSUE TITLE
Latest revision build fails

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#162]
Building the latest revision 9c8aa559a21ce4a367f7d6f2e1e64ce0099421c4 fails at the `cmake ..` command.

The complete list of commands to compile is given below
 ```bash
cd ./lib
cargo build
cargo test
cargo doc
cd ..

cargo install --force cbindgen
python -m pip install -e ./python[dev]

cd build
cmake -DCMAKE_C_COMPILER=gcc ..      # <- FAILURE
make
make check
cd ..
```

And the full error message can be found attached.
[cmake-error.txt](https://github.com/trueagi-io/hyperon-experimental/files/9309480/cmake-error.txt)

**Comment by ngeiswei** [comment]
Some info about my system:
OS AV MX-Linux 21
CMake 3.18.4
GCC 10.2.1
Python 3.9.2
Cargo 1.61.0

**Comment by vsbogd** [comment]
@ngeiswei, thank you for reporting! I have checked this on Ubuntu 18.04 with CMake 3.12 but it looks like I missed these error messages because app was built successfully anyway. Now I see that the `$<CONFIG:...> expression syntax I used was introduced only in latest versions of CMake. So, I will rewrite it using syntax which works for CMake 3.12.
