### ISSUE TITLE
Extension not working on custom types

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#316]
## Problem

Definition an `OperationAtom` extension does not seem to work if the type signature contains custom types.

## How to reproduce the problem

Create the following python file, `my-extension.py`:

```python
from hyperon.atoms import E, S, OperationAtom, ValueAtom
from hyperon.ext import *

def foo(x):
    print("foo(x={})".format(x))
    return E(S("Ctor"), ValueAtom(0.42))

@register_atoms
def my_function():
    return {'foo': OperationAtom('foo', foo, ['T', 'T'], True)}
```

Create the following metta file, `my-extension-test.metta`

```clojure
(: T Type)
(: Ctor (-> Number T))

!(extend-py! my-extension)
!(foo (Ctor 0.1))
```

Then run this file via `metta.py` (you may need to have those files under the same folder as `metta.py`)

```bash
python metta.py my-extension-test.metta
```

## What should be normally expected

```
foo(x=(Ctor 0.1))
[]
[(Ctor 0.42)]
```

## What is output instead

```
[]
[(foo (Ctor 0.1))]
```

This indicates that `foo` is not called.

## Remark

Note that if

```
!(foo (Ctor 0.1))
```

is replaced by

```
!(foo 0.1)
```

in `my-extension-test.metta`, and

```
    return {'foo': OperationAtom('foo', foo, ['T', 'T'], True)}
```

is replaced by

```
    return {'foo': OperationAtom('foo', foo, ['Number', 'Number'], True)}
```

in `my-extension.py`, then it outputs

```
foo(x=0.1)
[]
[(Ctor 0.42)]
```

indicating that problems comes from the custom type `T`.

I should also mention, though that might be another issue, that the output type of `foo`, after these replacements, was not checked, since it had no problem outputting `(Ctor 0.42)`, which is not of type `Number`.

**Comment by vsbogd** [comment]
The root cause is that last argument in `OperationAtom('foo', foo, ['T', 'T'], True)` is `True`. The name of the flag is `unwrap` and this flag means that grounded function expects grounded Python objects as arguments and Python API should automatically unwrap them from atoms. The code above passed the expression `(Ctor ...)` as input for `foo`, Python API checks that atom is not a grounded atom and raises `NoReduceError` exception which leads to `(foo ...)` call is not reduced:
https://github.com/trueagi-io/hyperon-experimental/blob/ec382262c824e4f3c97bd0464a39ad9cdb75d36a/python/hyperon/atoms.py#L160-L166
 `OperationAtom('foo', foo, ['T', 'T'], False)` works as expected.

Another small issue is that:
```python
def foo(x):
    print("foo(x={})".format(x))
    return E(S("Ctor"), ValueAtom(0.42))
```
shoudl return a list of atoms:
```python
def foo(x):
    print("foo(x={})".format(x))
    return [E(S("Ctor"), ValueAtom(0.42))]
```
but it is clearly reported by interpreter when first issue is fixed.

@Necr0x0Der I would suggest convert `NoReduceError` to the `RuntimeError` to stop interpreting the code and gracefully return error, what do you think?

**Comment by Necr0x0Der** [comment]
> I would suggest convert NoReduceError to the RuntimeError to stop interpreting the code and gracefully return error, what do you think?

Well, this behavior was intentional, and it is covered by unit tests, which will be broken if we change the behavior. It seems that we may need both types of behavior, and a better default behavior might be to return `RuntimeError` after all to reduce confusion. I think it is not a problem to add a flag to `OperationObject`, which can be used in `if not isinstance(arg, GroundedAtom)` in order to decide, what type of exception to return. But maybe, no one really needs `NoReduceError` for such expressions as `(+ my-symbol 5)` and we should just modify unit tests...

**Comment by vsbogd** [comment]
Unit test we have are:
- `(> 4 (+ ln 2))`
- `(> 4 (+ $x 2))`
- `((lambda $x (+ $x 1)) 2)`

To me first should return a type error, and other two should not be reduced. Thus `+` should have different behaviour in different context and flag on `OperationObject` will not solve this issue for `+`.

I think if `+` requires `Number` and it cannot do anything useful with anything else then it should not be called with anything which is a strict `Number`. It should be detected by interpreter and it should not try to call it on the first place. The reason why interpreter tries to reduce `(+ $x 4)` or `(+ ln 2)` is that `$x` or `ln` has type `%Undefined%` which can be matched with anything.

Thus we have three different situations when interpreter tries to match type of the grounded function and an argument before call:
- types are equal - function can be called
- types are not equal but can be matched - then call should be made and we should left expression non-reduced
- types cannot be matched - type error

**Comment by Necr0x0Der** [comment]
> To me first should return a type error

In this example, `ln` is `%Undefined%` as you noticed.

> types are not equal but can be matched - then call should be made and we should left expression non-reduced

Does it mean that `(> 4 (+ ln 2))` should remain unreduced after all? My idea was that MeTTa can work similarly to Wolfram - when an expression cannot be reduced, it simply remains unreduced. For example, we can write down `(+ 5 inf)` and keep it unreduced until we decide how to add numbers to infinity. I wanted the behavior of grounded functions to be similar to that of symbolic functions, i.e. the latter can be partial.
We may want to have even something like `(: inf Number)` and to define `(= (+ $x inf) inf)` later. That is, if a grounded function cannot process its input data (while it is declared to be of a right type), it returns `NoReduceError` and the interpreter tries to find symbolic equalities for it, and can keep it non-reduced if no such equalities are found.

**Comment by Necr0x0Der** [comment]
> we should be able to detect that type is not correct on interpreter level before grounded function is called

yes, I agree

> The grounded function itself anyway can return NoReduce if it finds it should do it

Well, yes, any grounded function can have `unwrap=False` and do all the necessary processing by itself and it can by itself decide whether to return `NoReduceError` or `RunTimeError`. So, the question is more about default behavior to ease implementation of grounded functions in extensions. I still think that there can be an additional flag in `OperationAtom` to customize the behavior for `unwrap=True`, and it's pretty easy to implement, but it seems to be not the root cause anyway, right?

**Comment by vsbogd** [comment]
> but it seems to be not the root cause anyway, right?

I you are right. I just realized that if interpreter detects the type error and prevents the grounded function call then the default behavior doesn't matter. And it looks like all this discussion is more about types then about default behavior of `unwrap`.

**Comment by ngeiswei** [comment]
I can confirm that it works on my side when setting `unwrap` to `False`.  

I'm therefore closing that issue and a separate one about type checking function calls may be raised if necessary.
