### ISSUE TITLE
Randomly fails to properly reduce a let statement involving function calls

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#323]
## What is the problem?

The MeTTa interpreter randomly fails to evaluate a let statement involving function calls.

## How to reproduce the problem?

Run the following code *multiple* times:

```clojure
;; Define foo
(= (foo A) A)
(= (foo B) B) ; Culprit

;; Define bar
(= (bar (D $x)) $x)

;; Test
!(let* (($x (C (foo $y) (bar $z)))
        ($y A)
        ($z (D 1)))
   $x)
```

It randomly fails.

## What should be normally expected?

```clojure
[(C A 1)]
```

## What is output instead?

```clojure
[(C A $X#14)]
```

## Remarks

Sometimes the output is correct and sometimes it is not.  It should be noted that after removing the line

```clojure
(= (foo B) B) ; Culprit
```

it succeeds all the time.

Shortening that code any further, such as replacing `(= (bar (D $x)) $x)` by `(= (bar $x) $x)` also fixes the random failure.

**Comment by vsbogd** [comment]
The root cause is a bug in a cache of the results inside an interpreter. It caches the result of `(bar $z)`. First execution returns `$X#11` with `{ $z <- (D $X#11) }`. Second execution returns `$X#14` with `{ $z <- (D $X#11) }`. Consequently one of the branches becomes `let $x (C A $X#14) (let* ((A A) ((D $X#11) (D 1))) $x))|{ $y <- A, $z <- (D $X#11) }` and contains both `$X#11` and `$X#14`.

**Comment by vsbogd** [comment]
More specifically the issue is that when cache value is returned then its variables are made unique. But if they are present in `Bindings` as well the instances in `Bindings` are not touched. This leads to the behavior above.
