### ISSUE TITLE
Should `Space` be a fundamental Atom type?

### ISSUE THREAD

**Issue by luketpeterson** [trueagi-io/hyperon-experimental#333]
This issue is a reminder to follow up on this question: https://github.com/trueagi-io/hyperon-experimental/pull/331#issuecomment-1592930275

Should there be 5 fundamental atom types? ie [Sym, Var, Expr, Grounded(FFI), Space]?

Currently, Space is implemented as a a grounded atom.  However this forces a few unnatural things.
1. Custom GroundedAtom types can't be assigned to Space GroundedAtoms because the type field is used to indicate it's a space.
2. The C API treats Spaces as special because there is no universal grounded atom data format
3. The Python API has special cases when wrapping a grounded atom or calling get_object() on a grounded atom.  And with native space atoms, we could avoid this wrapping / get_object() requirement.

So I see several good arguments for a 5th native atom type.  I don't see any arguments against it, but perhaps there are some.  So I'll let this issue age a while and we can see how we feel in a few months.

**Comment by vsbogd** [comment]
All three items are true for any grounded atom and not only for spaces. The issue is that if grounded atom contains a Python object it cannot be used in Rust function which takes the object of the similar Rust type as a parameter. For example one cannot pass Python integer as an argument to the Rust `+` function.

Thus I would rather think about solving this issue in general: how we could use Python grounded atoms within the Rust and vice versa.

The question whether something should be recognized as an unique meta-type is a question whether its has an unique interface which cannot be expressed otherwise in MeTTa. Spaces are important for MeTTa but on the other hand until now we expressed their interface via grounded atoms API successfully.

**Comment by luketpeterson** [comment]
> The issue is that if grounded atom contains a Python object it cannot be used in Rust function which takes the object of the similar Rust type as a parameter.

To me this feels like a slightly different question (although related).  In the most basic form, a Grounded atom exposes itself as an opaque object and any functions that need to care about that object's contents need to know how to deal with that object's format.

A Python integer is not the same thing as a Rust primitive i64.  One can be converted into the other, but first the code needs to know what it has.  It sounds like it's not core MeTTa's job to make that conversion.  (Maybe the MeTTa std library could provide this conversion, for common types like integers, to be friendly.)

In my opinion, Spaces are special is because Spaces are part of core MeTTa in a way that Integers and other FFI types aren't.  Also we provide the implementation for bridging them seamlessly between C, Python, and Rust, so we aren't relying on the user to interpret the grounded atom.

Another idea (I haven't thought through all the details yet) is to provide a universal convenience to take a grounded atom type and turn it into a native object.  Basically provide a universal bridging facility, so a module that exports a grounded atom type can also export converters for each host language.  (ie. code to turn the grounded atom into a native Rust type, Python type, etc.)  That would turn the special case for Space inside get_object() and G, into a general case.

**Comment by vsbogd** [comment]
> A Python integer is not the same thing as a Rust primitive i64. One can be converted into the other, but first the code needs to know what it has.

To me the space implemented in Python and space implemented in Rust are not the same either. 

> In my opinion, Spaces are special because Spaces are part of core MeTTa in a way that Integers and other FFI types aren't. 

Then we need to formulate this difference. My opinion the arguments about conversion of spaces and other grounded atoms are equal and could be covered by the same mechanism.

> Also we are the ones providing the implementation for bridging them seamlessly between C, Python, and Rust, so we aren't relying on the user to interpret the grounded atom's format.

We are bridging other grounded atoms as well. 

> Basically provide a universal bridging facility, so a module that exports a grounded atom type can also export converters for each host language. (ie. code to turn the grounded atom into a native Rust type, Python type, etc.) That would turn the special case for Space inside get_object() and G, into a general case.

Yes, it is what I  mean.

**Comment by luketpeterson** [comment]
> To me the space implemented in Python and space implemented in Rust are not the same either.

The current top-of-tree code will convert them so they both become a Rust `DynSpace` type no matter whether the atom came from Rust or C or Python.  That is the purpose of the bridging.  It eliminates the `CGrounded` wrapper that would otherwise wrap the non-bridged Python grounded atoms.

> We are bridging other grounded atoms as well.

What other types?  I would like to study this pattern but I am not sure exactly what you mean.

>> Basically provide a universal bridging facility, so a module that exports a grounded atom type can also export converters for each host language. (ie. code to turn the grounded atom into a native Rust type, Python type, etc.) That would turn the special case for Space inside get_object() and G, into a general case.

> Yes, it is what I mean.

Having an elegant interoperability with native types in the host language would make MeTTa a lot friendlier to use.  It will take some time to design this mechanism however, so perhaps other changes have a higher priority.  But I agree with this idea.

**Comment by vsbogd** [comment]
> The current top-of-tree code will convert them so they both become a Rust DynSpace type no matter whether the atom came from Rust or C or Python. That is the purpose of the bridging. It eliminates the CGrounded wrapper that would otherwise wrap the non-bridged Python grounded atoms.

I think bridging here is needed only because of Rust type system's restrictions. We have `CSpace` object to wrap Python and C space implementations. And it would be enough but Rust doesn't allow dynamic casting to the traits. If it would be possible then we would not need some special logic to convert C API spaces to the `DynSpace` type.

> What other types? I would like to study this pattern but I am not sure exactly what you mean.

Here I mean that `CGrounded` is a kind of such bridge. It provides necessary functions to manipulate Python grounded atoms from Rust. Basically at the very beginning I had a feeling it could be enough. Now it is obvious that it is not enough for the deep integration of grounded values and grounded functions written in different platforms. But it is still not clear whether we can find a universal way to integrate different platforms better. If we can do it then space is not that different in this aspect.
