### ISSUE TITLE
signification of unify

### ISSUE THREAD

**Issue by aymeric75** [trueagi-io/hyperon-experimental#334]
Hello,

Another question about the specification...

I don't see the symbol **unify** explained anywhere in the [spec](https://wiki.opencog.org/wikihome/images/b/b7/MeTTa_Specification.pdf). For instance, what does (unify (Human Socrates) (TV $p1)) means ?

Regards

**Comment by vsbogd** [comment]
Actually specification explains what `unify` is in the following sentense: `The pattern matcher will not recursively call itself. Instead, it will return a conditional match, in which the necessity for further unification of (+ 2 2) and 4 is indicated in the form of expression (unify (+ 2 2) 4) to be further evaluated.`

In fact `unify` isn't used in a current version of the interpreter. The reason is that it allows very arbitrary matches and thus slows down the interpreter significantly because of combinatorial explosion. For example consider the following case: `Such a query as (= (double $y) 4) will be matched against (= (double $x) (+ $x $x)) conditioned on (unify (+ $x $x) 4). Whether the latter can be successful or not depends on the definition and equalities of +` 
Matching of the `(= (double $y) 4)` and `(= (double $x) (+ $x $x))` returns the empty result. But when value of `$x` is determined and `(+ $x $x)` is found then in case of a successful match the value of `$y` is returned.

**Comment by aymeric75** [comment]
Thanks, I thing I get it. Matching ` (= (double $y) 4)` and `(= (double $x) (+ $x $x))` returns the empty results because no further evaluation is possible I guess.

**Comment by vsbogd** [comment]
>  Matching  `(= (double $y) 4)` and `(= (double $x) (+ $x $x))` returns the empty results because no further evaluation is possible I guess.

It is possible figure out the value of `$y` given `(= (double $y) 4)` and `(= (double $x) (+ $x $x))`, but additional rules are required. For example:  `(= (+ $x $x) (* 2 $x))` and `(= (= $z (* $x $y)) (= $y (/ $z $x)))`.
