### ISSUE TITLE
Improve Python API for Space

### ISSUE THREAD

**Issue by Necr0x0Der** [trueagi-io/hyperon-experimental#335]
This is a stream of thought in the course of inspecting Python Space API from #322. It is not a call for action, but question to discuss. 

#322 implemented Space API for Python, which works, but there is a bunch of classes, which number might be possible to reduce or systematize:

* `PySpace`
https://github.com/trueagi-io/hyperon-experimental/blob/8ee0262a1469c29094d49fd51c515646ae59a212/python/hyperon/base.py#L5 
seems to be not of much use.
`TestSpace`
https://github.com/trueagi-io/hyperon-experimental/blob/8ee0262a1469c29094d49fd51c515646ae59a212/python/tests/test_custom_space.py#L6
 inherits from it, but this inheritance is not used. `TestSpace` is wrapped into `Space`, which is wrapped into `G` to be used as an atom. `PySpace` contains fields `content` and `id`, which are typical for grounded objects (to be wrapped into `G` directly). First of all, if `PySpace` is supposed to be a class for space objects, then it would be better to call it `SpaceObject` and to place in `atoms.py` - not `base.py`. But since `TestSpace` is wrapped into `Space`, which doesn't use `content` field at all, so it seems that `PySpace` is simply redundant... or I'm missing something... If we want to have `PySpace` (or its renamed version) as an interface, we may want to add `add`, `remove`, `replace`, `query` etc methods, which should be implemented by the custom space.

* it is somewhat confusing that `TestSpace` has `add`, `remove`, etc. methods, which are called via `call_add_on_python_space`, and at the same time it is wrapped into `Space` that has `add_atom` etc calling `hp.space_add`, which redirects to `call_add_on_python_space`. This might be ok, but couldn't `TestSpace` inherit from `Space` and override `add_atom`, etc., so there is no need to redirect from `Space.add_atom` to `call_add_on_python_space` to `TestSpace.add`? For example, won't it be possible to reuse the storage and to reimplement only `query` if wanted?

* `GroundingSpace` inherits from `Space` and directly calls `hp.space_new_grounding` in the constructor. So, it seems that we already can redefine `query`, etc. Although there might be some issues with converting from `cspace` back to Python classes, but we solved this problem with separating grounded values from universal grounded atoms in Python.

**Comment by luketpeterson** [comment]
My thinking was this:

`Space` is the "front" interface to any space, regardless of whether it's implemented in Rust, C, or Python.  It's the object the "User" of a space sees.  Ie. the way atoms are added, removed, etc. and the way the space is queried directly.  It corresponds to `space_t` in the C API.

`GroundingSpace` is a special kind of space that specifically interfaces to the Rust implementation.

`PySpace` is a virtual class providing a "back" interface to implement a space in Python.  All Python spaces would inherit from that, and then implement the necessary methods.

`TestSpace` is just part of the test, It's a stand-in for an implementation a Python user might write, and not actually part of the API.

Perhaps we can either get rid of the `PySpace` object, and just document the methods a python object needs to implement in order to be registered as a space.  Or alternatively go the other direction, and provide implementations for every method that throw errors if they haven't been overridden.

Also, I'm open to renaming any of these objects if the current names are confusing.

**Comment by luketpeterson** [comment]
Regarding the need to wrap spaces in a Grounded Atom, see this discussion: https://github.com/trueagi-io/hyperon-experimental/issues/333

**Comment by vsbogd** [comment]
Well, our previous discussion with Luke is here https://github.com/trueagi-io/hyperon-experimental/pull/322#discussion_r1223599966.

The summary of my arguments:
- Calling Python space implementation through `Space` makes always proxying calls to the custom space via Python API (`client -> Space -> hyperonpy -> C API -> hyperonpy -> PySpace`), which is not a most effective way;
- Python developer is able to ignore `PySpace` and override `Space` methods directly and thus our code provides ways of doing both things, which is also confusing, basically what is expected in case of OOP: the developer implements some interface and uses it;
- Python developer is able to ignore `Space` and call custom space's methods directly from Python, thus this architecture doesn't prevents this kind of errors;
- `PySpace` interface is basically only keeping the space's `id` which looks surprisingly from OOP perspective;
- I agree that having two names for the methods `add` and `add_atom` in the same code in Python looks surprisingly as well;
- It works differently in Python and in Rust, in the last case a custom space structure reuses functionality by aggregating the `SpaceCommon` structure instead of being wrapped by some `SpaceCommon` structure.

And last thing doing it by one way (wrapping custom space by `SpaceCommon`) or another (aggregating `SpaceCommon`) we can actually provide a way to reuse functionality.

**Comment by Necr0x0Der** [comment]
So, what is the conclusion? Should I refactor the code to remove redundancy?

**Comment by luketpeterson** [comment]
> So, what is the conclusion? Should I refactor the code to remove redundancy?

I don't think we have a strong conclusion yet.  I see 3 separate questions.

1. Should Spaces be wrapped in GroundedAtoms or Native atoms?

That's being discussed here: https://github.com/trueagi-io/hyperon-experimental/issues/333 but for now we will leave them as grounded atoms

2. Should short-cut calling of Python spaces be allowed?  Ie. calling a Python space directly from Python without calling through the Rust dispatch code?  (See Vitaly's arguments above)?

In my opinion we will have a more maintainable and more flexible system if we don't allow short-cut calling.

This is part of my argument for keeping the method names different.  ie. the Space implements `add` but the user calls `space.add_atom()`.  The Space object is also a different kind of object than the space implementation passed to the `Space()` constructor.

Obviously we can't completely stop the user from calling their own functions, but if the user does the short-cut call then they are using the API incorrectly and it might break for them.  It's not different than reading memory after it's been freed in C... In other words it might appear to work, but that doesn't mean it's a valid thing to do.

3. What should we do about PySpace?

a.) Make it a virtual base-class by implementing all the space methods, and then throwing errors if those methods aren't overridden.
b.) Delete it

Either of these options is fine with me and I don't have an opinion either way.

**Comment by luketpeterson** [comment]
Thinking about this a bit more, 2 & 3 are connected.  If we allow short-cut calling, the we should totally delete `PySpace`.  If we decide not to allow it, then PySpace should become a virtual base class.

**Comment by luketpeterson** [comment]
It seems to me that there is a deeper philosophical question at the heart of the issue about whether "short-cut calling" should be allowable.

There are two different philosophies, and we need to pick one.

1.) There is a "core interpreter system" implemented in Rust, and the C and Python bindings are a way to access the underlying Rust MeTTa functionality.  MeTTa could be extended with modules in the other languages, but the Rust core is still the ultimate arbiter of all functionality.  This same philosophy is used by most mature embeddable language libraries, eg. Python, JavaScript (V8), Lua, etc.

The advantages to approach 1 is that the overall system will be much faster (execution speed) and more maintainable (functionality centralized as much as possible).

2.) Any functionality that conforms to the MeTTa spec can be implemented in any language.  In this philosophy all implementation languages are peers - the Rust library isn't special.  At the limit, the user could replace any part of the system with a module implemented in any language.  Maybe the Rust library could be completely optional, at some point in the future.

The advantage to approach 2 is that it's faster to hack and experiment with deep changes to fundamental MeTTa constructs.

**Comment by vsbogd** [comment]
Thanks Luke. What is not clear to me: why do you put approach of calling Python space's methods only via C API  and approach of allowing calling Python space's API directly via Python methods as opposite or mutually exclusive directions.

As far as I understand your point is that if we make users wrap their instances of spaces into our `Space` wrapper (let's say it is approach (1)) then later we can change the functionality of the custom space (modifying `Space`)  without requiring users to re-implement it.

If we allow directly inherit `Space` and override its methods (approach (2)) or allow calling custom implementations directly then we have restricted abilities of modifying the logic of the custom spaces. We still can modify logic which was in place before custom space was added but cannot add new logic (new methods for example) without asking users to modify their implementations.

Do I understand your point correctly?

**Comment by luketpeterson** [comment]
Right.  Approach 1 gives us the more central control over the behavior of all spaces.

If we keep approach 1, then I think we either want to change PySpace to either:
A.) Have methods that throw errors, letting the implementor know they need to override them all. or
B.) Have methods that call through to GroundingSpace, giving the implementor the ability to just override one method (e.g. query)

Also, what about changing the name of PySpace to `SpaceImpl`, to be more clear that it's not a type of space but the object to inherit from if you want to make your own space?

**Comment by luketpeterson** [comment]
Does https://github.com/trueagi-io/hyperon-experimental/pull/345 address the issues well enough?  Can this issue be closed or are there more needed improvements that you see?

Thanks.

**Comment by Necr0x0Der** [comment]
I think it is good enough for now. So, let's close this PR via #345
