### ISSUE TITLE
Bug launching metta with empty PYTHONPATH

### ISSUE THREAD

**Issue by DaddyWesker** [trueagi-io/hyperon-experimental#386]
After a call with @vsbogd  and telling him about my bug on launching metta examples from python/sandbox/numpy directory (see pic below) we've decided to open an issue.

![Screenshot from 2023-08-03 14-02-58](https://github.com/trueagi-io/hyperon-experimental/assets/10774222/21eac18f-84ef-4376-9c28-64841782199b)

I've also added printing of sys.path so the problem can be seen more clearly. In my case sys.path doesn't contain folder  `~/SingularityNet/MeTTa/hyperon-experimental/python/sandbox/numpy` from which I'm launching metta file. @vsbogd  was able to reproduce this bug by emptying his PYTHONPATH environment variable (in my case it is empty by default, in his case - it contains something, including `' '` (current dir)). 

I was able to come with a solution to this proble, though I don't know if it is appropriate one. In `python/hyperon/runner.py` I've tried to add `sys.path.append(os.sep.join(path[:-1]))` under `os.chdir(os.sep.join(path[:-1]))` line in the `import_file` function and now it works for me. Though, as I understand, it can't be allowed to add paths like that since in some large project with multiple numpy imports inside metta files we will add many paths to sys.path. Though some sort of memory of previous sys.path could be used to restore sys.path to it's previous state just like with `os.chdir(prev_cwd)`.

@Necr0x0Der

**Comment by vsbogd** [comment]
The issue is that when `metta something.metta` is called Python fills the first item of the `sys.path` by the path to the `metta.py` script. This behaviour is described in [sys.path documentation](https://docs.python.org/3.9/library/sys.html#sys.path). Thus current working directory by default is not a part of the Python `sys.path` and MeTTa interpreter cannot import Python modules which are located in the same directory where `.metta` script is located.

The question is should we consider this a bug or not. One the one hand frequently people expect that Python module will be loaded when it is in the current working directory. On the other hand it is not a default behaviour of the Python interpreter.

**Comment by luketpeterson** [comment]
The platform environment object, introduced with the repl changes, contains search paths that are independent of Python's search paths.  These paths are explored by the python runner, and result in the dependency being found.

**Comment by luketpeterson** [comment]
Confirmed to work in top-of-tree with both the REPL and the "metta.py" launcher script.
