### ISSUE TITLE
imported file causes BorrowError crash

### ISSUE THREAD

**Issue by patham9** [trueagi-io/hyperon-experimental#397]
run.metta:
```
(= (maketrouble $C $T) (add-atom &self crash))
!(import! &self moretrouble.metta)
```

moretrouble.metta:
```
(= ($A realtrouble $A) $A)
```

`metta run.metta` causes:

```
thread '<unnamed>' panicked at 'already mutably borrowed: BorrowError', /Users/paha9538/hyperon-experimental/lib/src/space/mod.rs:296:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
Abort trap: 6
```

**Comment by Necr0x0Der** [comment]
Very strange behavior. I minimized run.metta :
```
(= (maketrouble $C $T) &self)
!(import! &self crash.metta)
```
No Rust panic if we replace `&self` with anything else. No panic if we replace `(= ($A realtrouble $A) $A)` with `(= (realtrouble $A $A) $A)`. No panic if we replace `(= (maketrouble $C $T) &self)` with `(= (maketrouble C $T) &self)`... Apparently, the first expression in run.metta somehow interferes with the expression in moretrouble.metta , which is strange, because these expressions are not evaluated. Maybe, there is a problem with hashing (e.g. hashing function tries to address `&self` in the expression while importing in `&self`), but this is a non-informed guess. Rust logs should be examined to understand the reason...

**Comment by luketpeterson** [comment]
This doesn't occur with `import`.  I'm going to keep this open to see if the problem happens with `include`

**Comment by vsbogd** [comment]
Don't see it is reproducible with both `import!` and `include`
