### ISSUE TITLE
Need HyperonPy version when Hyperon isn't installed via pip

### ISSUE THREAD

**Issue by luketpeterson** [trueagi-io/hyperon-experimental#434]
Following up on https://github.com/trueagi-io/hyperon-experimental/issues/417, the problem is that when the library isn't installed via pip, the version is "unkown".  An accurate version should be reflected somehow regardless of the installation method.

From @Necr0x0Der on Mattermost:
> But I don't want to use pip install at all. Why can't I run metta with a freshly built hyperonpy library, which is just placed in PATH? Relying on pip is kind of restricting.

**Comment by wenwei-dev** [comment]
In my opinion, if Python code is in edit mode, using the version number to check compatibility is not a reliable method, as changes can be made to the code at any time. 
If you prefer, we can manually assign a version. However, this will require manual maintenance, as opposed to automatic updates. So if we want it to tell the version anyway, my question is what version it should be?

**Comment by vsbogd** [comment]
If getting version from a distribution package like it is programmed now in the `__init__.py` doesn't work: https://github.com/trueagi-io/hyperon-experimental/blob/95f742aeab30811ef9b9964b94462a9a7d77314b/python/hyperon/__init__.py#L5-L17
We can switch to manual version assignment as Luke also proposed above. For example we could put version into `__init__.py`. I believe `setuptools_scm` should be able to obey this version. For such solution we also need to modify `release-python.yml` because if we move version into `__init__.py` then we cannot get it from the tag anymore. Vice versa we need to form tag from this version.

**Comment by vsbogd** [comment]
> In my opinion, if Python code is in edit mode, using the version number to check compatibility is not a reliable method, as changes can be made to the code at any time.

When user uses Python module installed in editable mode or builds the project from sources he should understand what he is doing. Checking version even in this mode makes sense to ensure that absolutely different version is not loaded instead. Making changes in Python code of the library user knows that it can break the system in a whole. Thus if check is successful but something is broken user should understand that it can be caused by local changes.
