### ISSUE TITLE
Errors inside MeTTa runner C bindings shouldn't panic

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#465]
currently repl fails with error "Unexpected end of expression" when  if multi-line expression is pasted

example  
```
metta>         (= (reverse $Xs $Ys)
thread '<unnamed>' panicked at src/metta.rs:936:27:
Returning errors from C API is not implemented yet: "Unexpected end of expression"
```

**Comment by noskill** [comment]
interpreter just need to count parenthesises  and interpret only when the expression is closed

**Comment by luketpeterson** [comment]
Parse errors are now piped through C correctly when interacting directly with the parser.  This issue is that the runner functions (e.g. `metta_run`) just panic on those errors.

I'd like to keep this issue open and close the other one, as this issue actually deals with runner errors, whereas the other issue was for parser errors.

**Comment by luketpeterson** [comment]
NOTE: This fix should be implemented for both the `metta_t` object (`metta_run`, `metta_evaluate_atom`, and `metta_load_module`) as well as the `runner_state_t` object (`runner_state_step`)

**Comment by Necr0x0Der** [comment]
> I'd like to keep this issue open and close the other one

OK, makes sense

**Comment by luketpeterson** [comment]
With the https://github.com/trueagi-io/hyperon-experimental/pull/471/commits changes, the errors are catchable.

**Comment by luketpeterson** [comment]
I believe this should be done.  Assigning to @noskill to verify.
