### ISSUE TITLE
Performant way to do pair-wise queries / joins

### ISSUE THREAD

**Issue by nasser** [trueagi-io/hyperon-experimental#810]
given an attribute in an `(attribute entity value)` set of triples i want to be able to discover other "related attributes." the approach i am exploring is to find what other attributes entities that share the attribute in question also share and have equal values.

```
(= (discover $rule)
   (let* (($c1 (match &self ($rule $c me) $c))                    ;; all entities matching the attribute $rule
          ($c2 (match &self ($rule $c me) $c))                    ;; "clone" of $c1
          (($a $b) (unify ($c1 $c2) ($x $x) (empty) ($c1 $c2)))   ;; pairs of entities that are not equal
          ($aa (match &self ($attr $a $val) ($attr $val)))        ;; (attribute value) for every entity $a
          ($bb (match &self ($attr $b $val) ($attr $val))))       ;; (attribute value) for every entity $b
         (unify ($aa $bb) ($x $x) $x (empty))))                   ;; return all equal (attribute value)

(cousin adam me)
(cousin eden me)

(likes adam coloring)
(likes eden coloring)

(age adam 8)
(age eden 11)

(father adam bill)
(father eden bill)

(likes adam movies)
(likes eden movies)

! (discover cousin)
;; [[(likes movies), (likes coloring), (father bill), (cousin me), (likes coloring), (likes movies), (father bill), (cousin me)]]
```

this works fine, but it runs at ~300ms for a very small data set. adding assertions grows the runtime. i imagine i am causing some kind of combinatorial explosion in the lookup mechanism given the number of `match`s and `unify`s but it is not clear how else to approach this. this feels like a database join or some other kind of pair-wise comparison/query. guidance would be very appreciated!

**Comment by vsbogd** [comment]
I will explain it in three steps because I think each one has some useful tips.

**Step 1.** One can use `collapse`/`superpose` to remove duplicated query, it should be faster than querying second time especially on a large database. Also last `unify` can be replaced by using the results of the last but one query inside last query.
```
(= (discover $rule)
   (let* (($cs (collapse (match &self ($rule $c me) $c)))         ;; all entities matching the attribute $rule
          ($c1 (superpose $cs))                                   ;; "clone" of $cs
          ($c2 (superpose $cs))                                   ;; "clone" of $cs
          (($a $b) (unify ($c1 $c2) ($x $x) (empty) ($c1 $c2)))   ;; pairs of entities that are not equal
          (($attr $val) (match &self ($attr $a $val) ($attr $val))) ;; (attribute value) for every entity $a
          ($x (match &self ($attr $b $val) ($attr $val))))        ;; (attribute value) for every entity $b
         $x))                                                     ;; return all equal (attribute value)
```

**Step 2.** One can also use `,` (intersection) operator inside queries to implement a duplication and finding equal (attribute value) pairs.
```
(= (discover $rule)
   (let* ((($c1 $c2) (match &self (, ($rule $c1 me) ($rule $c2 me)) ($c1 $c2))) ;; all entities matching the attribute $rule cloned
          (($a $b) (unify ($c1 $c2) ($x $x) (empty) ($c1 $c2)))                 ;; pairs of entities that are not equal
          ($x (match &self (, ($attr $a $val) ($attr $b $val)) ($attr $val))))  ;; equal (attribute value) for every entity $a and $b
         $x))                                                                   ;; return all equal (attribute value)
```

**Step 3.** Using `,` allow rewriting it in more clear form which in fact gives the best performance (more than 10 times faster on my machine), despite each sub-query of `,` in fact is executed as a separate query. Here we make a single query to get all the data and then use `unify` to add `AND-NOT` condition.
```
(= (discover $rule)
  (match &self
    (,                                              ;; intersect results of sub-queries
      ($rule $a me)                                 ;; all entities matching the attribute $rule
      ($rule $b me)                                 ;; copy all entities matching the attribute $rule
      ($attr $a $val)                               ;; (attribute value) for every entity $a
      ($attr $b $val))                              ;; (attribute value) for every entity $b
    (unify ($a $b) ($x $x) (empty) ($attr $val))))  ;; pairs of entities that are not equal
```

**Comment by vsbogd** [comment]
> despite each sub-query of , in fact is executed as a separate query

Here I mean there is no sophisticated query engine in the current hyperon-experimental space implementation to optimize the query like `(, ($rule $a me) ($rule $b me))` and doing it more effectively than making the first sub-query then making the second one and intersect the results.

**Comment by vsbogd** [comment]
Interesting that if we apply `superpose`/`collapse` trick one more time to remove duplicates of sub-queries like this:
```
(= (discover $rule)
  (let* (
    ($c (collapse (match &self (, ($rule $a me) ($attr $a $val)) ($attr $a $val)))) ;; getting all possible (attribute value) pairs for entities
    (($attr $a $val) (superpose $c))                                                ;; make first non-deterministic copy
    (($attr $b $val) (superpose $c)))                                               ;; make second non-deterministic copy
    (unify ($a $b) ($x $x) (empty) ($attr $val))))                                  ;; filter out only non-equal entities
```
The performance returns to the original one, i.e. ~300ms for query on my machine. Nevertheless I am adding this example because I am not sure which of this will be faster on a bigger amount of data.

@nasser if you can test it and provide results it would be interesting.
