### ISSUE TITLE
Atomspace query doesn't return result because of variable names conflict

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#84]
```
(= (append Nil $x1 $x1) True) 
 
(= (append (Cons $X1 $Y) $Z (Cons $X1 $W)) 
  (append $Y $Z $W) 
)
```
Working prints True
```
!(println! (append (Cons a2 Nil) (Cons b1 Nil) $W2222)) 
```

not working 
```
!(println! (append (Cons a2 Nil) (Cons b1 Nil) $W))
```

**Comment by noskill** [comment]
The same issue is present with recursion:
```
(= (mylist Nil)
   True)

(= (mylist (Cons $a $b))
   (mylist $b))

!(println! (mylist $W))
```
Here (mylist $W) is an infinite list, but recusion fails when $b is matched with (Cons $a $b)

**Comment by vsbogd** [comment]
It happens because when matching atomspace atoms we forbid results which express variables via itself. This is a hack for examples like following:
```
        (= (eq $x $x) True)
        (= (plus Z $y) $y)
        (= (plus (S $k) $y) (S (plus $k $y)))

        !(println! (eq (plus (S Z) $y) $y))
```
where on the last step the expression `(eq (S $y) $y)` will be matched with `(= (eq $x $x) True)`, because $x <- (S $y), $y <- $x, and after applying bindings to bindings we will have $y <- (S $y).

Two things can be fixed here:
1. we could prevent the loop from variables which happens when we are trying to match `(eq (S $y) $y)` with `(= (eq $x $x) True)`;
2. we could make variable names for a candidates unique when matching happens.

Second item is enough to fix the issue in the description, but it raises another issue. When we are comparing two expressions with variables like: `(eq (S $y) $y)` it may happen that they are different only by variable names. So we need separate procedure to compare atoms in unit tests taking this into account.

**Comment by noskill** [comment]
on how prolog deals with the issue https://stackoverflow.com/questions/9358623/variable-names-in-swi-prolog

**Comment by vsbogd** [comment]
To elaborate previous comment further. The simplest example I made to reproduce issue:
```
(= (a ($w)) True)
!(println! (a $w))
```
It matches `(a $w)` with `(a ($w))` by assigning `$w <- ($w)` and it is detected as a variable loop while it is actually not, because variables are from different scopes and should not be considered as the same variable. Renaming variables in the candidate expression before matching fixes this, new result is: `$w <- ($w-42)` and no confusion happens.

But renamed variables can sneak into interpreted expression like in the following example:
```
(= (b ($x $y)) (c $x $y))
!(println! (a (b $a) $x $y))
```
After matching `(b $a)` with renaming we will have `$a <- ($x-1 $y-1) /* ($x $y) from candidate */` and final result will be: `(a (c $x-1 $y-1) $x $y)`. Here all four variables are different. 

We have similar but simpler examples in our unit tests when after test assertion just checks two expressions with variables for equality. But this asserts do not work after renaming. We can equality check by equivalence check however. For instance we can match two atoms and check that they are matched and all bindings bind variables to another variables. For the example above:
`(a (c $x-1 $y-1) $x $y))` and `(a (c $a $b) $c $d)` are matched with bindings: `$a <- $x-1, $b <- $y-1, $c <- $x, $d <- $y`.

**Comment by vsbogd** [comment]
To put it clear, I already have fix for the second item from https://github.com/trueagi-io/hyperon-experimental/issues/84#issuecomment-1145588666 but to have green tests we need to solve issue with matching variables after renaming explained in https://github.com/trueagi-io/hyperon-experimental/issues/84#issuecomment-1145905373

**Comment by Necr0x0Der** [comment]
For me, retrieving KB variable names as bindings for query variables looks exotic for now. While it may occur in practice of programming in MeTTa, but we may want to discourage programmers from binding variables to variables and from retrieving variable names, which have only local meaning (in contrast to variables in more traditional languages). We might encounter some use for such the retrieval in meta-programming, but maybe this would be solvable by reinterpreting variable symbols as `Atom` types. Basically, I wouldn't consider this
```
  left: Ok([(eq (S $y-770) $y-770)])
 right: Ok([(eq (S $y) $y)])
```
as failures now and just rework corresponding unit tests until we really find need for this.
